- name: Ansible Tower build deployment
  hosts: all
  tasks:
    - name: Build download build
      get_url:
        url: http://172.18.200.140/builds/index.html.gz
        dest: /tmp

    - name: Ansible Tower deploy build
      command: mv /tmp/index.html.gz /var/www/html/nginx/index.html.gz

    - name: Remove old files
      command: rm /var/www/html/nginx/index.html

    - name: Ansible Tower uncompress build
      shell: gunzip /var/www/html/nginx/index.html1.gz
